### ISSUE TITLE
Move the console into piksi_tools.console

### ISSUE THREAD

**Issue by mfine** [swift-nav/piksi_tools#10]
The console clutters up the main tools area - its hard disambiguating what's a script vs what's part of the console (views, etc.) plus all the installer stuff. What about moving the console into its own directory? `piksi_tools.console`. Might help think about whats in the tools directory better.

/cc @fnoble @denniszollo @mookerji

**Comment by mookerji** [comment]
I think this is a unanimously popular idea.
