### ISSUE TITLE
clang: error: unknown argument: '-framework ApplicationServices'

### ISSUE THREAD

**Issue by makslevental** [swift-nav/piksi_tools#1078]
also

`clang: error: unknown argument: '-framework OpenGL'`

somehow related to this?

https://github.com/enthought/enable/pull/335

please advise @silverjam

**Comment by silverjam** [comment]
Hello @makslevental, it could be related, can you describe where you're seeing the error?  Also, if possible I would use a released version of the console from https://support.swiftnav.com/customer/en/portal/articles/2492795-swift-console -- however, the version of the `enable` library that the console builds against *should* have this issue fixed.

**Comment by silverjam** [comment]
Hi @makslevental -- as I mentioned on another ticket, please open a support request through support@swiftnav.com if the released version of the console doesn't work out (it definitely should though!).
