### ISSUE TITLE
there is literally no way to make this work

### ISSUE THREAD

**Issue by makslevental** [swift-nav/piksi_tools#1079]
i've tried multiple commit hashes, multiple branches, both py2 and py3, and due to various errors it becomes clear that this tool no longer works at all. nice to know that a $2000 board comes with no software support *after* purchasing.

**Comment by silverjam** [comment]
Hello @makslevental, please contact support@swiftnav.com for support requests.  Additionally we haven't design this repository to be consumed by end-users.  Released versions of the Swift Console are available here: https://support.swiftnav.com/customer/en/portal/articles/2756825-installing-swift-console.
