### ISSUE TITLE
Updating firmware over internet using Console leads to timeout

### ISSUE THREAD

**Issue by jarledo** [swift-nav/piksi_tools#1271]
## Problem

We're using Swift Console to debug and update remote devices through ssh port forwarding., i.e. we have remote ssh access to a remote machine running Linux which is on the same local network as the Piksi Multi GNSS module. This is done using the following command with the default IP and port for Piksi:

```console
ssh -N -L 55555:192.168.0.222:55555 user@remote.host.ip
```

This allows us to connect to the Piksi module using Swift Console with TCP/IP address localhost:55555. This works very well, except for when updating firmware. At around 82% we get the error:

```
Transferring image to device...

82.8 % of 19.1 MB transferred.
Failed to transfer image file to Piksi: Timed out

Upgrade Aborted.
```

and in the Console Log:

```
Traceback (most recent call last):
  File "piksi_tools\console\update_view.py", line 804, in manage_multi_firmware_update
  File "piksi_tools\fileio.py", line 570, in write
  File "piksi_tools\fileio.py", line 361, in send
  File "piksi_tools\fileio.py", line 377, in _send
  File "piksi_tools\fileio.py", line 341, in _wait_window_available
  File "piksi_tools\fileio.py", line 290, in _check_pending
Exception: Timed out
```

Screenshot:

<img width="851" alt="image" src="https://user-images.githubusercontent.com/57762990/171392918-d3c67df1-3ab1-435f-a258-0076a2d48e17.png">

## Possible Solution

It reaches 82% after about 63 seconds every time. This timeout seems a bit strict, it's making steady progress all the way up to 82% without any slowdowns. Would it be possible to increase this timeout to allow for uploading on slower connections? By tracing the traceback it seems to be limited by the `MAXIMUM_RETRIES = 20` variable here: https://github.com/swift-nav/piksi_tools/blob/07a895ca91b3b1e168550a1a207a18b3e7d13450/piksi_tools/fileio.py#L289

This would explain the 63 seconds timeout, as 21 * 3 s = 63 s

**Comment by samvrlewis** [comment]
Hi @jarledo, thanks for letting us know about this issue! It definitely looks like your proposed solution is the right fix but would you please contact our support team (via https://support.swiftnav.com/support/tickets/new) and someone on the team will be able to follow up with you directly. We have a (currently unreleased) new version of the updater that should solve this issue.
