### ISSUE TITLE
Console: in Solution tab, instruct user to turn on Basestation mode for RTK subtab

### ISSUE THREAD

**Issue by drewshannon** [swift-nav/piksi_tools#135]
Currently, if Basestation mode is off, the RTK Position subtab (within Solution tab) simply shows no data.  There needs to be an indication for how to use this feature.

**Comment by drewshannon** [comment]
![screen shot 2015-07-22 at 5 31 47 pm](https://cloud.githubusercontent.com/assets/9704961/8840904/4b2bd474-309c-11e5-969f-5d85b619d034.png)

**Comment by cbeighley** [comment]
![image](https://cloud.githubusercontent.com/assets/502385/8840933/84eab4be-309c-11e5-8974-f9e2d413beec.png)

**Comment by denniszollo** [comment]
closed:
![image](https://cloud.githubusercontent.com/assets/11276774/14257630/9917d3fa-fa53-11e5-887f-683f65540030.png)
