### ISSUE TITLE
Update documentation for console changes

### ISSUE THREAD

**Issue by denniszollo** [swift-nav/piksi_tools#167]
We will need to replace or crop screenshots that show the message window or the update screen before we release a new version of the console.
- Clever Idea is to so some image manipulation and just replace the bottom half of the screen on all the screenshots with the new looking msg table.  
- Firmware update instructions will need some love as well as this screen was reshuffled.

@robhranac, @drewshannon

**Comment by denniszollo** [comment]
New console looks like this:

![image](https://cloud.githubusercontent.com/assets/11276774/9413712/7cb5dedc-47e8-11e5-8a83-47378e802a54.png)

**Comment by denniszollo** [comment]
![image](https://cloud.githubusercontent.com/assets/11276774/9413720/8e0bea3c-47e8-11e5-8059-19014ec1adf1.png)

**Comment by sashamitelman** [comment]
I added my own suggestions in #182.

**Comment by sashamitelman** [comment]
I didn't see this initially, so I added my own suggestions in #182.

**Comment by denniszollo** [comment]
@drewshannon , @rai-swiftnav , @robhranac 
As the documentation team, we need to audit documentation for compatibility with the new look of the firmware update team.
