### ISSUE TITLE
Piksi User Getting Started Guide proposed edits

### ISSUE THREAD

**Issue by sashamitelman** [swift-nav/piksi_tools#182]
- Unclear whether or not it is safe to hot-plug the Piksi to the host PC (USB) and/or the 3DR 915 MHz radios. Would be good to state this in the instructions, especially if there's any risk of damaging the electronics by doing so.
- Under the "Viewing position solutions" section, the text describing the tracking tab states "This simulation shows that you are tracking 8 satellites; you know this because you will see consistent C/No of over 33 dB-Hz." The corresponding screenshot shows 9SVs. Also, the statement "consistent C/N0 of over 33 dBHz" does not necessarily follow from the number of SVs tracked; is this just stating our acquisition threshold?
- The screenshot for "Baseline tab" and the accompanying text description differ from the output of the current Console build. ("Rover path" and "Rover Relative Position" are replaced with "RTK Fixed" and "RTK Float," respectively, and the blue trace is not shown in the current build's demo run.)
- (Video generally) Screenshot of desktop is cut off (note that folder in upper right goes off edge of screen) and text in example windows is either blurry (if Vimeo HD is switched off) or crisp, but very small (if HD is switched on).
- (Video @ 1:22) “Confirm that you’re running the latest firmware build” — should suggest that user notes the newest build number when doing the FW update, otherwise they will have to stop and look this info up on the fly.
- (Video @ 3:03) Time to do RTK. Should explicitly mention that one Piksi will be the base, the other the rover. (This terminology is used without much explanation in demonstrating simulated RTK mode @ 2:11)
- (Video @ 3:11) Should note that the colored dot on the antenna doesn’t seem to do anything. Just make sure RP SMA connectors are finger tight and point the antenna more or less up (at short range it won’t matter).

**Comment by denniszollo** [comment]
@drewshannon for the next video rev

**Comment by robhranac** [comment]
We're going to no op para 1.  Paragraph 2 is now updated.  Paragraph 3 is problematic, so I am keeping this open.  All others are video revs that are no ops for now.

**Comment by sashamitelman** [comment]
May I suggest adding a few Amadana-style illustrations to the antenna
placement guidelines?

http://gizmodo.com/339479/amadanas-warning-illustrations-are-something-special
