### ISSUE TITLE
Observation tab showing old observations

### ISSUE THREAD

**Issue by benjamin0** [swift-nav/piksi_tools#383]
Once a signal's observations make their way into the Observation pane, they don't disappear even if we stop observing that signal.

![image](https://cloud.githubusercontent.com/assets/6760058/21033876/ae56cb44-bd68-11e6-97f7-dfa3fb04bd7b.png)

@denniszollo

**Comment by ljbade** [comment]
Working on a fix in https://github.com/swift-nav/piksi_tools/pull/386
