### ISSUE TITLE
rinex converter support in console

### ISSUE THREAD

**Issue by denniszollo** [swift-nav/piksi_tools#395]
Add a new tab called "data converters" in advanced tab

Proposed functionality: 

- Open sbp.json file (or binary file)
- Choose output filename
- Choose converter output flavor
- Press convert

Initial flavor: Rinex 2.1
future flavors:  RTCMv3, csv, NMEA, KML

Use sbp2rinex shell and Rinex documentation (available online for free)

Testing strategy:

test static roof Rinex in RTKLib and other 3rd party tools

**Comment by jkretzmer** [comment]
Closed, no longer applicable.
