### ISSUE TITLE
Unexpected tracking channel legend behavior in console

### ISSUE THREAD

**Issue by wltr** [swift-nav/piksi_tools#403]
The tracking legend seems to have duplicates and not display tracking channel use correctly.

![screenshot from 2016-12-16 17-04-34](https://cloud.githubusercontent.com/assets/822983/21283180/2155d3b0-c3b3-11e6-9885-933623bfdddf.png)
![screenshot from 2016-12-16 17-13-53](https://cloud.githubusercontent.com/assets/822983/21283181/215a06ba-c3b3-11e6-87a2-f6d975d8f851.png)

**Comment by denniszollo** [comment]
there is a new legend entry for items that are dropped on one channel and come back on a different channel.  The legend entry doesn't go away until that item scrolls out of the history (200 tracking interations later).  

How do you think it should work?

**Comment by denniszollo** [comment]
Ok, I agree that it should just have the most recent channel in the legend.  But I do think your tracking performance must have been really bad in order to see a legend that long.
