### ISSUE TITLE
Download Latest Firmware saves file in \Program Files folder on Windows

### ISSUE THREAD

**Issue by switanis** [swift-nav/piksi_tools#483]
Download Latest Firmware saves file in \Program Files folder on Windows when no folder is specified.

It also displays is incorrectly:
Saved file to C:\PROGRA~2\SWIFTN~1\SWIFTC~1\PiksiMulti-v1.0.11.bin

**Comment by denniszollo** [comment]
This pull request should fix the issue.  Tested on OSX thus far.

https://github.com/swift-nav/piksi_tools/pull/505
