### ISSUE TITLE
Console does not work well with no write permissions in "program files" on Windows

### ISSUE THREAD

**Issue by denniszollo** [swift-nav/piksi_tools#51]
See user reported issue here: https://groups.google.com/forum/#!topic/swiftnav-discuss/LrziO_m60ms

When we add the option to choose location of output data files, we should also add option of choosing download location of firmware and/or any other temporary files.

**Comment by switanis** [comment]
Can use

C:\Users\<username>\Documents\Swift Navigation\Firmware
or
C:\Users\<username>\Documents\Swift Navigation\Downloads

as default.

**Comment by denniszollo** [comment]
Should be resolved with new status bar.  No logfile is opened automatically.
