### ISSUE TITLE
console shows PRN+1 instead of PRN

### ISSUE THREAD

**Issue by mbavaro** [swift-nav/piksi_tools#615]
The new tracking state message uses `gnss_signal16_t` where the PRN is already 1-based. I think the console is adding 1 to that (conforming with the previous `MSG_TRACKING_STATE`)

**Comment by mbavaro** [comment]
in case this is the right thing to do (I am fairly convinced it is), here is the PR:
https://github.com/swift-nav/piksi_tools/pull/616

**Comment by Paakkit** [comment]
Indeed we have thing like PRN33 appearing in console.

![prn33](https://user-images.githubusercontent.com/17005823/28106517-cdf4ef2a-66ec-11e7-89bf-937172e62bf6.png)

**Comment by ljbade** [comment]
Wow this has been an issue for a while I believe, nice work!

**Comment by mbavaro** [comment]
Keerthan will embrace this change in the next PR, closing as we verify all is gone well!
