### ISSUE TITLE
Put an annotation in the "RTK Position" tab of the console indicating what settings are required for the tab to display information.

### ISSUE THREAD

**Issue by denniszollo** [swift-nav/piksi_tools#62]

**Comment by denniszollo** [comment]
Or perhaps we hide the tab until the message is received.

**Comment by sashamitelman** [comment]
Hiding the tab may be less than obvious to non-expert users.

Suggest leaving it exposed, but either greying out its contents, displaying a message (ideally in bold or colored text) saying "RTK Fix needed to enable these options," or both.
