### ISSUE TITLE
Button to start SBP log recording from the console

### ISSUE THREAD

**Issue by fnoble** [swift-nav/piksi_tools#63]
Right now we can start logging RINEX with a button but SBP logs must be initiated from the command line. We need an easier way for people to start an SBP log from the GUI.

**Comment by denniszollo** [comment]
+1.  Also, filename prefix and location choosing capability.

**Comment by mookerji** [comment]
+1

It would be cool to have a rolling appender that always kept track of the last n minutes.

**Comment by switanis** [comment]
Related to #150
