### ISSUE TITLE
python3 incompatibility

### ISSUE THREAD

**Issue by makslevental** [swift-nav/piksi_tools#996]
https://github.com/swift-nav/piksi_tools/blob/v2.2.0-release/piksi_tools/settings.py#L246

should be 

`        section, setting, value, format_type = sbp_msg.payload[2:].split(b'\0')[:4]`

and https://github.com/swift-nav/piksi_tools/blob/v2.2.0-release/piksi_tools/settings.py#L123

should be

`            for setting, value in self.settings_list[section].items():`

**Comment by silverjam** [comment]
Hi @makslevental, the `v2.3.0-release` branch should have better Python 3 compatibility, we did work to enable Python 3 compatibility in this release and in release 2.5.0 of libsbp.
